site_name: Tensorlake
theme:
  name: material
  logo: 'assets/logo.png'
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  language: en
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline 
        name: Switch to dark mode
      primary: teal
      accent: purple 
    - scheme: slate 
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode    
      primary: teal
      accent: lime

plugins:
  - search

nav:
  - Home: index.md
  - API Documentation: redocly.md
  - Python SDK: generated.md

extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/tensorlakeai
    - icon: fontawesome/brands/twitter
      link: https://x.com/tensorlake
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/company/tensorlake/

markdown_extensions:
- pymdownx.highlight:
    anchor_linenums: true
- pymdownx.inlinehilite
- pymdownx.snippets
- admonition
- pymdownx.arithmatex:
    generic: true
- footnotes
- pymdownx.details
- pymdownx.superfences
- pymdownx.mark
- attr_list

extra_javascript:
  - https://cdn.redoc.ly/redoc/latest/bundles/redoc.standalone.js
  - custom.js

extra_css:
  - extra.css

copyright: |
  &copy; 2024 <a href="https://www.linkedin.com/company/tensorlake/"  target="_blank" rel="noopener">Tensorlake</a>